sinclude(project/build/ac-macros/ccache.m4)
sinclude(project/build/ac-macros/depends.m4)
sinclude(project/build/ac-macros/expat.m4)
sinclude(project/build/ac-macros/boost.m4)
sinclude(project/build/ac-macros/antlr.m4)
sinclude(project/build/ac-macros/examples.m4)
sinclude(project/build/ac-macros/curl.m4)
