FILE(GLOB LIB_SOURCES ${CMAKE_SOURCE_DIR}/project/librets/src/*.cpp)

IF(LIBRETS_BUILD_SQL_COMPILER AND ANTLR_FOUND)
  # Add the generated sql files
  # ADD_COMMAND
  # FILE(GLOB GENERATED_SOURCES *** WHERE THE FUCK ARE THEY ***)
  # INCLUDE_DIRECTORIES(${GENERATED_DIR})
  # Add the static SQL files.
  FILE(GLOB SQL_SOURCES ${CMAKE_SOURCE_DIR}/projects/librets/sql/*.cpp)
ENDIF(LIBRETS_BUILD_SQL_COMPILER AND ANTLR_FOUND)

SET(LIBRETS_SOURCES ${LIB_SOURCES} ${SQL_SOURCES} ${GENERATED_SOURCES})
