libRETS: md5::digest_type Class Reference
md5::digest_type Class Reference
A message digest.
#include <boostext/md5.hpp>
Public Types
typedef uint8_t value_type [16]
typedef char hex_str_value_type [33]
Public Member Functions
digest_type ()
digest_type (const value_type &a_value)
digest_type (const hex_str_value_type &a_hex_str_value)
digest_type (const digest_type &a)
void reset ()
void reset (const value_type &a_value)
void reset (const hex_str_value_type &a_hex_str_value)
digest_type & operator= (const digest_type &a)
const value_type & value () const
const hex_str_value_type & hex_str_value () const
~digest_type ()
Detailed Description
A message digest.
Member Typedef Documentation
typedef char hex_str_value_type[33]
typedef uint8_t value_type[16]
Constructor & Destructor Documentation
digest_type () inline
References md5::digest_type::reset().
digest_type (const value_type & a_value) inline
References md5::digest_type::reset().
digest_type (const hex_str_value_type & a_hex_str_value) inline
References md5::digest_type::reset().
digest_type (const digest_type & a) inline
References md5::digest_type::reset().
~digest_type () inline
References md5::digest_type::reset().
Member Function Documentation
const hex_str_value_type& hex_str_value () const
digest_type& operator= (const digest_type & a) inline
References md5::digest_type::reset().
void reset () inline
Referenced by md5::digest_type::digest_type(), md5::digest_type::operator=(), and md5::digest_type::~digest_type().
void reset (const value_type & a_value) inline
void reset (const hex_str_value_type & a_hex_str_value)
const value_type& value () const inline
Referenced by boostext::operator==().
Generated by